using namespace std;
	void opening()
{
Sleep(1000);
cout << "                      BUS TICKET MANAGEMENT SYSTEM." << endl;
Sleep(1300);
cout << "                                Presented by " << endl;
Sleep(1500);
cout << "                                Asad Abbas" << endl;

}
void quit()
{
system("cls");
cout << endl << endl << endl;
cout << "              ***************************************************" << endl;
cout << "              *                                                 *" << endl;
cout << "              *                                                 *" << endl;
cout << "              *   Thank you for stopping by. Have a good day.   *" << endl;
cout << "              *                                                 *" << endl;
cout << "              *                                                 *" << endl;
cout << "              ***************************************************" << endl << endl;
}
void bus()
{
cout << "                           " << endl;
cout << "      ____________________ " << endl;
cout << "     (   [ ]   [ ]   [ ] |)" << endl; 
cout << "ELS==(__ ______________ _|)" << endl;
cout << "        O              O   " << endl;
cout << "                           " << endl;
Sleep(300);
system("cls");
cout << "                            " << endl;
cout << "       ____________________ " << endl;
cout << "      (   [ ]   [ ]   [ ] |)" << endl; 
cout << "VELS==(__ ______________ _|)" << endl;
cout << "         O               O  " << endl;
cout << "                            " << endl;
Sleep(50);
system("cls");
cout << "                             " << endl;
cout << "        ____________________ " << endl;
cout << "       (   [ ]   [ ]   [ ] |)" << endl; 
cout << "AVELS==(__ ______________ _|)" << endl;
cout << "          O              O   " << endl;
cout << "                             " << endl;
Sleep(50);
system("cls");
cout << "                              " << endl;
cout << "         ____________________ " << endl;
cout << "        (   [ ]   [ ]   [ ] |)" << endl; 
cout << "RAVELS==(__ ______________ _|)" << endl;
cout << "           O              O   " << endl;
cout << "                              " << endl;
Sleep(50);
system("cls");
cout << "                               " << endl;
cout << "          ____________________ " << endl;
cout << "         (   [ ]   [ ]   [ ] |)" << endl; 
cout << "TRAVELS==(__ ______________ _|)" << endl;
cout << "            O              O   " << endl;
cout << "                               " << endl;
Sleep(50);
system("cls");
cout << "                                " << endl;
cout << "           ____________________ " << endl;
cout << "          (   [ ]   [ ]   [ ] |)" << endl; 
cout << " TRAVELS==(__ ______________ _|)" << endl;
cout << "             O              O   " << endl;
cout << "                                " << endl;
Sleep(50);
system("cls");
cout << "                                 " << endl;
cout << "            ____________________ " << endl;
cout << "           (   [ ]   [ ]   [ ] |)" << endl; 
cout << "D TRAVELS==(__ ______________ _|)" << endl;
cout << "              O              O   " << endl;
cout << "                                 " << endl;
Sleep(50);
system("cls");
cout << "                                  " << endl;
cout << "             ____________________ " << endl;
cout << "            (   [ ]   [ ]   [ ] |)" << endl; 
cout << "AD TRAVELS==(__ ______________ _|)" << endl;
cout << "               O              O   " << endl;
cout << "                                  " << endl;
Sleep(50);
system("cls");
cout << "                                   " << endl;
cout << "              ____________________ " << endl;
cout << "             (   [ ]   [ ]   [ ] |)" << endl; 
cout << "SAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                O              O   " << endl;
cout << "                                   " << endl;
Sleep(50);
system("cls");
cout << "                                    " << endl;
cout << "               ____________________ " << endl;
cout << "              (   [ ]   [ ]   [ ] |)" << endl; 
cout << "ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                 O              O   " << endl;
cout << "                                    " << endl;
Sleep(50);
system("cls");
cout << "                                     " << endl;
cout << "                ____________________ " << endl;
cout << "               (   [ ]   [ ]   [ ] |)" << endl; 
cout << " ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                  O              O   " << endl;
cout << "                                     " << endl;
Sleep(50);
system("cls");
cout << "                                      " << endl;
cout << "                 ____________________ " << endl;
cout << "                (   [ ]   [ ]   [ ] |)" << endl; 
cout << "  ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                   O              O   " << endl;
cout << "                                      " << endl;
Sleep(50);
system("cls");
cout << "                                       " << endl;
cout << "                  ____________________ " << endl;
cout << "                 (   [ ]   [ ]   [ ] |)" << endl; 
cout << "   ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                    O              O   " << endl;
cout << "                                       " << endl;
Sleep(50);
system("cls");
cout << "                                        " << endl;
cout << "                   ____________________ " << endl;
cout << "                  (   [ ]   [ ]   [ ] |)" << endl; 
cout << "    ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                     O              O   " << endl;
cout << "                                        " << endl;
Sleep(50);
system("cls");
cout << "                                         " << endl;
cout << "                    ____________________ " << endl;
cout << "                   (   [ ]   [ ]   [ ] |)" << endl; 
cout << "     ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                      O              O   " << endl;
cout << "                                         " << endl;
Sleep(50);
system("cls");
cout << "                                          " << endl;
cout << "                     ____________________ " << endl;
cout << "                    (   [ ]   [ ]   [ ] |)" << endl; 
cout << "      ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                       O              O   " << endl;
cout << "                                          " << endl;
Sleep(50);
system("cls");
cout << "                                           " << endl;
cout << "                      ____________________ " << endl;
cout << "                     (   [ ]   [ ]   [ ] |)" << endl; 
cout << "       ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                        O              O   " << endl;
cout << "                                           " << endl;
Sleep(50);
system("cls");
cout << "                                            " << endl;
cout << "                       ____________________ " << endl;
cout << "                      (   [ ]   [ ]   [ ] |)" << endl; 
cout << "        ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                         O              O   " << endl;
cout << "                                            " << endl;
Sleep(50);
system("cls");
cout << "                                             " << endl;
cout << "                        ____________________ " << endl;
cout << "                       (   [ ]   [ ]   [ ] |)" << endl; 
cout << "         ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                          O              O   " << endl;
cout << "                                             " << endl;
Sleep(50);
system("cls");
cout << "                                              " << endl;
cout << "                         ____________________ " << endl;
cout << "                        (   [ ]   [ ]   [ ] |)" << endl; 
cout << "          ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                           O              O   " << endl;
cout << "                                              " << endl;
Sleep(50);
system("cls");
cout << "                                               " << endl;
cout << "                          ____________________ " << endl;
cout << "                         (   [ ]   [ ]   [ ] |)" << endl; 
cout << "           ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                            O              O   " << endl;
cout << "                                               " << endl;
Sleep(50);
system("cls");
cout << "                                                " << endl;
cout << "                           ____________________ " << endl;
cout << "                          (   [ ]   [ ]   [ ] |)" << endl; 
cout << "            ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                             O              O   " << endl;
cout << "                                                " << endl;
Sleep(50);
system("cls");
cout << "                                                 " << endl;
cout << "                            ____________________ " << endl;
cout << "                           (   [ ]   [ ]   [ ] |)" << endl; 
cout << "             ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                              O              O   " << endl;
cout << "                                                 " << endl;
Sleep(50);
system("cls");
cout << "                                                  " << endl;
cout << "                             ____________________ " << endl;
cout << "                            (   [ ]   [ ]   [ ] |)" << endl; 
cout << "              ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                               O              O   " << endl;
cout << "                                                  " << endl;
Sleep(50);
system("cls");
cout << "                                                   " << endl;
cout << "                              ____________________ " << endl;
cout << "                             (   [ ]   [ ]   [ ] |)" << endl; 
cout << "               ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                O              O   " << endl;
cout << "                                                   " << endl;
Sleep(50);
system("cls");
cout << "                                                    " << endl;
cout << "                               ____________________ " << endl;
cout << "                              (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                 O              O   " << endl;
cout << "                                                    " << endl;
Sleep(50);
system("cls");
cout << "                                                     " << endl;
cout << "                                ____________________ " << endl;
cout << "                               (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                 ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                  O              O   " << endl;
cout << "                                                     " << endl;
Sleep(50);
system("cls");
cout << "                                                      " << endl;
cout << "                                 ____________________ " << endl;
cout << "                                (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                  ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                   O              O   " << endl;
cout << "                                                      " << endl;
Sleep(50);
system("cls");
cout << "                                                       " << endl;
cout << "                                  ____________________ " << endl;
cout << "                                 (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                   ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                    O              O   " << endl;
cout << "                                                       " << endl;
Sleep(50);
system("cls");
cout << "                                                        " << endl;
cout << "                                   ____________________ " << endl;
cout << "                                  (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                    ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                     O              O   " << endl;
cout << "                                                        " << endl;
Sleep(50);
system("cls");
cout << "                                                         " << endl;
cout << "                                    ____________________ " << endl;
cout << "                                   (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                     ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                      O              O   " << endl;
cout << "                                                         " << endl;
Sleep(50);
system("cls");
cout << "                                                          " << endl;
cout << "                                     ____________________ " << endl;
cout << "                                    (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                      ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                       O              O   " << endl;
cout << "                                                          " << endl;
Sleep(50);
system("cls");
cout << "                                                           " << endl;
cout << "                                      ____________________ " << endl;
cout << "                                     (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                       ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                        O              O   " << endl;
cout << "                                                           " << endl;
Sleep(50);
system("cls");
cout << "                                                            " << endl;
cout << "                                       ____________________ " << endl;
cout << "                                      (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                        ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                         O              O   " << endl;
cout << "                                                            " << endl;
Sleep(50);
system("cls");
cout << "                                                             " << endl;
cout << "                                        ____________________ " << endl;
cout << "                                       (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                         ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                          O              O   " << endl;
cout << "                                                             " << endl;
Sleep(50);
system("cls");
cout << "                                                              " << endl;
cout << "                                         ____________________ " << endl;
cout << "                                        (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                          ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                           O              O   " << endl;
cout << "                                                              " << endl;
Sleep(50);
system("cls");
cout << "                                                               " << endl;
cout << "                                          ____________________ " << endl;
cout << "                                         (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                           ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                            O              O   " << endl;
cout << "                                                               " << endl;
Sleep(50);
system("cls");
cout << "                                                                " << endl;
cout << "                                           ____________________ " << endl;
cout << "                                          (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                            ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                             O              O   " << endl;
cout << "                                                                " << endl;
Sleep(50);
system("cls");
cout << "                                                                 " << endl;
cout << "                                            ____________________ " << endl;
cout << "                                           (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                             ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                              O              O   " << endl;
cout << "                                                                 " << endl;
Sleep(50);
system("cls");
cout << "                                                                  " << endl;
cout << "                                             ____________________ " << endl;
cout << "                                            (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                              ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                               O              O   " << endl;
cout << "                                                                  " << endl;
Sleep(50);
system("cls");
cout << "                                                                   " << endl;
cout << "                                              ____________________ " << endl;
cout << "                                             (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                               ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                                O              O   " << endl;
cout << "                                                                   " << endl;
Sleep(50);
system("cls");
cout << "                                                                    " << endl;
cout << "                                               ____________________ " << endl;
cout << "                                              (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                                ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                                 O              O   " << endl;
cout << "                                                                    " << endl;
Sleep(50);
system("cls");
cout << "                                                                     " << endl;
cout << "                                                ____________________ " << endl;
cout << "                                               (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                                 ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                                  O              O   " << endl;
cout << "                                                                     " << endl;
Sleep(50);
system("cls");
cout << "                                                                      " << endl;
cout << "                                                 ____________________ " << endl;
cout << "                                                (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                                  ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                                   O              O   " << endl;
cout << "                                                                      " << endl;
Sleep(50);
system("cls");
cout << "                                                                       " << endl;
cout << "                                                  ____________________ " << endl;
cout << "                                                 (   [ ]   [ ]   [ ] |)" << endl; 
cout << "                                   ASAD TRAVELS==(__ ______________ _|)" << endl;
cout << "                                                    O              O   " << endl;
cout << "                                                                       " << endl;
}
